<?php echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <?php echo $this->headMeta(); ?>
    <meta http-equiv="content-language" content="en" />
    <meta name="robots" content="noindex,nofollow" />
    <title>Log BoomPrice</title>
</head>
<body>
    <div style="width:1000px;margin:auto;height:auto;border:1px solid blue;">
				tstst
    </div>
    <div style="width:1000px;margin:auto;height:auto;border:1px solid blue;overflow:hidden">
        
	<?php echo $this->layout()->content; ?>
        <?php 
            foreach ($this->flashmessages as $value) {
                var_dump($value);
            }
        ?>
    </div>
</body>
</html>

